In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('/Users/nanda/Downloads/Data Files/2. ST Academy - Classification models resource files/House-Price.csv',header=0)

In [3]:
from sklearn.linear_model import LogisticRegression

In [7]:
clf_lrs = LogisticRegression()

In [5]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [6]:
X= df[['price']]
y = df['Sold']

In [22]:
df.isnull().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
Sold           0
dtype: int64

In [8]:
clf_lrs.fit(X,y)

LogisticRegression()

In [9]:
clf_lrs.coef_

array([[-0.03571865]])

In [10]:
clf_lrs.intercept_

array([0.61477516])

In [12]:
import statsmodels.api as sn

In [13]:
X_cons = sn.add_constant(X)

In [14]:
import statsmodels.discrete.discrete_model as sm

In [16]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [17]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Wed, 03 May 2023   Pseudo R-squ.:                 0.01788
Time:                        15:39:30   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

## Logistc with multiple predictors

In [46]:
X = df.loc[:,df.columns != 'Sold']

In [47]:
y = df['Sold']

In [48]:
clf_lr = LogisticRegression()

In [49]:
df = pd.get_dummies(df)

In [50]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop  n_hos_beds  n_hot_rooms  rainfall     parks  Sold  \
0      24.7       4.98       5.480      11.1920        23  0.049347     0   
1      22.2       9.14       7.332      12.1728        42  0.046146     1   
2      22.2       4.03       7.394     101.1200        38  0.045764     0   
3      21.3       2.94       9.268      11.2672        45  0.047151     0   
4      21.3       5.33       8.824      11.2896        55  0.039474     0   

   airport_YES  waterbody_Lake  waterbody_Lake and River  waterbody_River  
0            1               0                         0                1  
1            0               1                         0                0  
2            0               0                         0                0  
3            1               1                         0                0  
4            0               1                         0                0

In [51]:
list_not_req = ['airport_NO','waterbody_None','bus_ter_YES']

In [52]:
#df = df.drop(list_not_req,axis=1)

In [53]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop  n_hos_beds  n_hot_rooms  rainfall     parks  Sold  \
0      24.7       4.98       5.480      11.1920        23  0.049347     0   
1      22.2       9.14       7.332      12.1728        42  0.046146     1   
2      22.2       4.03       7.394     101.1200        38  0.045764     0   
3      21.3       2.94       9.268      11.2672        45  0.047151     0   
4      21.3       5.33       8.824      11.2896        55  0.039474     0   

   airport_YES  waterbody_Lake  waterbody_Lake and River  waterbody_River  
0            1               0                         0                1  
1            0               1                         0                0  
2            0               0                         0                0  
3            1               1                         0                0  
4            0               1                         0                0

In [54]:
df = df.fillna(df.mean())

In [55]:
clf_lr.fit(X,y)

/Users/nanda/miniforge3/envs/env_new/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [56]:
clf_lr.coef_

array([[-0.24779048, -0.01791499, -0.07233031,  0.85943004, -0.00575359,
         0.0251411 , -0.1160303 , -0.01007792, -0.2277017 ,  0.23228078,
        -0.21280009,  0.15751643, -0.08707119, -0.00614246, -0.00313841,
        -0.08489559, -0.11978067, -0.01823098,  0.22452421]])

In [57]:
clf_lr.intercept_

array([0.02709994])

In [58]:
X_cons = sn.add_constant(X)

In [60]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.549617
         Iterations 7


In [62]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      486
Method:                           MLE   Df Model:                           19
Date:                Wed, 03 May 2023   Pseudo R-squ.:                  0.2023
Time:                        15:51:09   Log-Likelihood:                -278.11
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 1.142e-20
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -3.2938      2.724     -1.209      0.227      -8.632       2.045
price                       -0.2798      0.034     -8.302      0.000      -0.346      -0.214
resid_area                   0.0175      0.027      0.649      0.517      -0.035       0.071
air_qual                    -7.6736      2.734     -2.807      0.005     -13.031      -2.316
room_num                     1.1522      0.283      4.071      0.000       0.597       1.707
age                         -0.0025      0.007     -0.377      0.706      -0.016       0.011
dist1                        1.2639      0.865      1.462      0.144      -0.431       2.959
dist2                       -1.5700      0.925     -1.698      0.090      -3.383       0.243
dist3                        0.8565      0.907      0.944      0.345      -0.922       2.635
dist4                       -0.9695      0.500     -1.939      0.053      -1.950       0.011
teachers                     0.3172      0.064      4.920      0.000       0.191       0.444
poor_prop                   -0.2080      0.034     -6.104      0.000      -0.275      -0.141
n_hos_beds                   0.1854      0.073      2.555      0.011       0.043       0.328
n_hot_rooms                 -0.0588      0.053     -1.106      0.269      -0.163       0.045
rainfall                    -0.0020      0.009     -0.230      0.818      -0.019       0.015
parks                       31.6675     24.545      1.290      0.197     -16.440      79.775
airport_YES                 -0.1981      0.213     -0.929      0.353      -0.616       0.220
waterbody_Lake              -0.0481      0.308     -0.156      0.876      -0.651       0.555
waterbody_Lake and River    -0.0111      0.332     -0.034      0.973      -0.661       0.639
waterbody_River              0.2651      0.258      1.027      0.305      -0.241       0.771
============================================================================================
"""

## LDA

In [112]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [113]:
clf_lda = LinearDiscriminantAnalysis()

In [114]:
clf_lda.fit(X,y)

LinearDiscriminantAnalysis()

In [115]:
y_pred_lda = clf_lda.predict(X)

In [116]:
from sklearn.metrics import confusion_matrix,roc_auc_score,accuracy_score

In [117]:
confusion_matrix(y,y_pred_lda)

array([[201,  75],
       [ 76, 154]])

In [118]:
roc_auc_score(y,y_pred_lda)

0.6989130434782609

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [121]:
clf_LR = LogisticRegression()

In [122]:
clf_LR.fit(X_train,y_train)

/Users/nanda/miniforge3/envs/env_new/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [123]:
y_test_pred = clf_LR.predict(X_test)

In [124]:
accuracy_score(y_test,y_test_pred)

0.6372549019607843

In [125]:
confusion_matrix(y_test,y_test_pred)

array([[37, 21],
       [16, 28]])

## K Nearest Neighbours

In [126]:
from sklearn.preprocessing import StandardScaler

In [127]:
scaler = StandardScaler().fit(X_train)

In [128]:
X_train_s = scaler.transform(X_train)

In [129]:
scaler = StandardScaler().fit(X_test)
X_test_s = scaler.transform(X_test)

In [130]:
from sklearn.neighbors import KNeighborsClassifier

In [131]:
clf_knn1 = KNeighborsClassifier(n_neighbors=1,n_jobs=-1)
clf_knn1.fit(X_train_s,y_train)

KNeighborsClassifier(n_jobs=-1, n_neighbors=1)

In [132]:
y_pred =clf_knn1.predict(X_test_s)

AttributeError: 'NoneType' object has no attribute 'split'

In [105]:
X_test.shape

(102, 19)

In [107]:
y_test.shape

(102,)

In [108]:
null_count = np.count_nonzero(np.isin(X_test_s, [None]))

print(null_count)

0


In [100]:
df.isnull().sum()

price                       0
resid_area                  0
air_qual                    0
room_num                    0
age                         0
dist1                       0
dist2                       0
dist3                       0
dist4                       0
teachers                    0
poor_prop                   0
n_hos_beds                  0
n_hot_rooms                 0
rainfall                    0
parks                       0
Sold                        0
airport_YES                 0
waterbody_Lake              0
waterbody_Lake and River    0
waterbody_River             0
dtype: int64

In [111]:
np.count_nonzero(np.isin(X_test_s, [None]))

0