## Support Vector for Regression

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
df = pd.read_csv("/Users/nanda/Downloads/Data Files/4. ST Academy - SVM resource files/Movie_regression.csv",header=0)

In [7]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget   
0            20.1264               59.62               0.462  36524.125  \
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating   
0         138.7               7.825                8.095            7.910  \
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken   
0            7.995           7.94         527367          YES      109.60  \
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [132]:
df.shape

(506, 21)

In [9]:
df.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
dtype: int64

In [10]:
df["Time_taken"].fillna( df.Time_taken.mean(),inplace=True)

In [11]:
df.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
dtype: int64

In [12]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget   
0            20.1264               59.62               0.462  36524.125  \
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating   
0         138.7               7.825                8.095            7.910  \
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken   
0            7.995           7.94         527367          YES      109.60  \
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

## Creating Dummy Values

In [13]:
df = pd.get_dummies(df,columns=["3D_available","Genre"],drop_first=True)

In [14]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget   
0            20.1264               59.62               0.462  36524.125  \
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating   
0         138.7               7.825                8.095            7.910  \
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags   
0            7.995           7.94         527367      109.60          223.840  \
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy   
0              23            494       48000              True         False  \
1              42            462       43200             False         False   
2              38            458       69400             False          True   
3              45            472       66800              True         False   
4              55            395       72400             False         False   

   Genre_Drama  Genre_Thriller  
0        False            True  
1         True           False  
2        False           False  
3         True           False  
4         True           False

In [133]:
df.shape

(506, 21)

# X-y Split

In [15]:
X = df.loc[:,df.columns!= "Collection"]

In [16]:
y = df.Collection

## Splitting into Train and Test data


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state= 0)

## Standardizing the Data

In [19]:
# mean = 0, variance = 1
from sklearn.preprocessing import StandardScaler  

In [20]:
sc = StandardScaler().fit(X_train)

In [21]:
X_train_std = sc.transform(X_train)

In [22]:
X_test_std = sc.transform(X_test)

In [23]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

## SVM Regression

In [24]:
from sklearn.svm import SVR

In [25]:
svr = SVR(kernel="linear",C = 1000)

In [26]:
svr.fit(X_train_std,y_train)

SVR(C=1000, kernel='linear')

## Predicting the values 

In [27]:
y_test_pred = svr.predict(X_test_std)
y_train_pred = svr.predict(X_train_std)

## Model Performance

In [28]:
from sklearn.metrics import r2_score,mean_squared_error

In [29]:
r2_score(y_test,y_test_pred)

0.502513572868267

In [30]:
r2_score(y_train,y_train_pred)

0.7124450931551861

In [31]:
mean_squared_error(y_test,y_test_pred)

160153135.3940456

In [32]:
mean_squared_error(y_train,y_train_pred)

97829380.08703768

 ## Fine tuning the Model

In [54]:
params_grid = {"C":[1,100,200,500,750,1000,2000,3000],'epsilon':[0.1,1,10,100],'kernel':['linear','rbf','poly']}

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
svr = SVR()

In [57]:
grid_search= GridSearchCV(svr,param_grid=params_grid,cv = 5)

In [58]:
grid_search.fit(X_train_std,y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 100, 200, 500, 750, 1000, 2000, 3000],
                         'epsilon': [0.1, 1, 10, 100],
                         'kernel': ['linear', 'rbf', 'poly']})

In [59]:
grid_search.best_params_

{'C': 500, 'epsilon': 100, 'kernel': 'linear'}

In [60]:
best_estim = grid_search.best_estimator_

In [61]:
best_estim.fit(X_train_std,y_train)

SVR(C=500, epsilon=100, kernel='linear')

In [62]:
r2_score(y_train,best_estim.predict(X_train_std))

0.7121104890363003

In [63]:
r2_score(y_test,best_estim.predict(X_test_std))

0.5034796629739359

In [64]:
mean_squared_error(y_train,best_estim.predict(X_train_std))

97943216.13276665

In [65]:
mean_squared_error(y_test,best_estim.predict(X_test_std))

159842127.19149408

## Support Vector Classifier

In [135]:
df = pd.read_csv("/Users/nanda/Downloads/Data Files/4. ST Academy - SVM resource files/Movie_classification.csv",header=0)

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [137]:
df.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [138]:
df["Time_taken"] = df.Time_taken.fillna(df["Time_taken"].mean())

In [139]:
df.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [140]:
df= pd.get_dummies(df,columns=["3D_available",'Genre'],drop_first=True)

In [141]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget   
0            20.1264               59.62               0.462  36524.125  \
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating   
0         138.7               7.825                8.095            7.910  \
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags   
0            7.995           7.94  ...      109.60          223.840  \
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar   
0              23            494       48000                 1  \
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0              True         False        False            True  
1             False         False         True           False  
2             False          True        False           False  
3              True         False         True           False  
4             False         False         True           False  

[5 rows x 21 columns]

X-y Split

In [142]:
X = df.loc[:,df.columns!='Start_Tech_Oscar']

In [143]:
y = df['Start_Tech_Oscar']

 ## Train Test Splir

In [144]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [145]:
from sklearn.preprocessing import StandardScaler

In [146]:
sc = StandardScaler().fit(X_train)

In [147]:
X_train_std = sc.transform(X_train)

In [148]:
X_test_std = sc.transform(X_test)

In [149]:
X_test_std.shape,y_test.shape

((102, 20), (102,))

## SVM Classification Model

In [150]:
from sklearn.svm import SVC
clf_svm_1 = SVC(kernel ='linear',C = 0.01)

In [151]:
clf_svm_1.fit(X_train_std,y_train)

SVC(C=0.01, kernel='linear')

## Model Performance

In [152]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [153]:
confusion_matrix(y_train,clf_svm_1.predict(X_train_std))

array([[ 33, 153],
       [  6, 212]])

In [154]:
accuracy_score(y_train,clf_svm_1.predict(X_train_std))

0.6064356435643564

In [155]:
confusion_matrix(y_test,clf_svm_1.predict(X_test_std))

array([[11, 33],
       [ 5, 53]])

In [156]:
accuracy_score(y_test,clf_svm_1.predict(X_test_std))

0.6274509803921569

In [158]:
clf_svm_1.n_support_

array([186, 189], dtype=int32)

## Hyper parameter tuning using Grid Search CV

In [164]:
params = {'C':[0.001,0.01,0.1,1 ,10,100,200,500,1000,2000,5000,10000],'kernel':['linear','rbf','poly'],'degree':[1,2,3,4]}

In [165]:
clf_svc2 = SVC()

In [166]:
grid_search = GridSearchCV(clf_svc2,params,n_jobs=-1,cv=10,verbose=1,scoring='accuracy')

In [167]:
grid_search.fit(X_train_std,y_train)

Fitting 10 folds for each of 144 candidates, totalling 1440 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 200, 500, 1000,
                               2000, 5000, 10000],
                         'degree': [1, 2, 3, 4],
                         'kernel': ['linear', 'rbf', 'poly']},
             scoring='accuracy', verbose=1)

In [169]:
grid_search.best_params_

{'C': 0.1, 'degree': 1, 'kernel': 'linear'}

In [170]:
best_estim = grid_search.best_estimator_

In [171]:
best_estim.fit(X_train_std,y_train)

SVC(C=0.1, degree=1, kernel='linear')

In [172]:
confusion_matrix(y_test,best_estim.predict(X_test_std))

array([[25, 19],
       [22, 36]])

In [173]:
accuracy_score(y_test,best_estim.predict(X_test_std))

0.5980392156862745

## Using the polynomial Kernel

In [177]:
clf_svc3 = SVC(C= 0.1,kernel='poly',degree=2)

In [178]:
clf_svc3.fit(X_train_std,y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [179]:
accuracy_score(y_test,clf_svc3.predict(X_test_std))

0.5588235294117647

In [180]:
clf_svc3.n_support_

array([185, 194], dtype=int32)

## Using Radial Kernel


In [181]:
clf_svc4 = SVC(C =0.1, kernel='rbf',gamma=0.5)

In [183]:
clf_svc4.fit(X_train_std,y_train)

SVC(C=0.1, gamma=0.5)

In [184]:
accuracy_score(y_test,clf_svc4.predict(X_test_std))

0.5686274509803921

## Using Grid Search